name: Test server

on: ["push", "pull_request"]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and start docker-compose
        run: docker compose up -d --build

      - name: List running containers
        run: docker ps

      - name: Show web logs
        run: docker logs minesweeper_web

      - name: Wait for web server
        run: sleep 3

      - name: Show web logs
        run: docker logs minesweeper_web

      - name: Echo logs
        run: cat app.log

      - name: Run integration tests
        run: python client.py

      - name: Stop docker-compose
        run: docker compose down
